# Generated by Django 3.1.3 on 2020-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField()),
                ('created_new', models.DateTimeField(auto_now_add=True)),
                ('updated_new', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='NewPhoto/%Y/%m/%d')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
